version: "3.7"

services:
  database_desafio_testes_unitarios:
    image: postgres
    container_name: database_desafio_testes_unitarios
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin_api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_desafio_testes_unitarios
    depends_on:
      - database_desafio_testes_unitarios

volumes:
  pgdata:
    driver: local
